FROM debian:stretch

WORKDIR /usr/local/src
RUN set -ex \
    && apt-get update -qqy \
    && apt-get -qqy --no-install-recommends install \
        build-essential libtidy5 ruby-dev bundler git \
    && apt-get purge -y \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
COPY . .
RUN bundle install && rake
